name: CI Deploy to Live

on:
  push:
    branches: ['main']

  workflow_dispatch:

jobs:
  build-and-deploy:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v3

      # https://github.com/marketplace/actions/create-env-file
      - name: Make envfile
        uses: SpicyPizza/create-envfile@v2.0
        with:
          envkey_VITE_GOOGLE_MAPS_API: ${{ secrets.VITE_GOOGLE_MAPS_API }}
          envkey_BASE_URL: ${{ vars.BASE_URL }}
          fail_on_empty: true
          sort_keys: false

      - name: Build
        run: |
          npm ci
          npm run build:ci

      # https://github.com/marketplace/actions/ftp-deploy
      - name: Sync
        uses: SamKirkland/FTP-Deploy-Action@4.3.1
        with:
          protocol: ftps
          server: ${{ vars.FTP_SERVER }}
          server-dir: ${{ vars.FTP_SERVER_DIR }}
          username: ${{ vars.FTP_USERNAME }}
          password: ${{ secrets.FTP_PASSWORD }}
          local-dir: ./dist/
